import type { Collection, Project, Stat, TechFeature, TimelineEvent } from "@/types";

export const COLLECTIONS: Collection[] = [
  {
    id: "essence",
    name: "Essence Collection",
    description: "Minimalist architectural forms that redefine ambient illumination through precision engineering and geometric purity.",
    coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    productCount: 24,
    category: "interior",
    tags: ["minimalist", "architectural", "LED"],
    isFeatured: true,
    isNew: false,
  },
  {
    id: "aurora",
    name: "Aurora Series",
    description: "Inspired by atmospheric light phenomena, this collection brings cinematic drama to residential and hospitality spaces.",
    coverImage: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&q=80",
    productCount: 18,
    category: "pendant",
    tags: ["dramatic", "hospitality", "designer"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "terra",
    name: "Terra Landscape",
    description: "Weather-resistant outdoor fixtures engineered for IP67 performance, transforming exterior environments into illuminated experiences.",
    coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    productCount: 31,
    category: "landscape",
    tags: ["outdoor", "IP67", "architectural"],
    isFeatured: false,
    isNew: false,
  },
  {
    id: "meridian",
    name: "Meridian Track",
    description: "Professional-grade track lighting systems delivering surgical precision for retail, gallery, and commercial applications.",
    coverImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
    productCount: 42,
    category: "track",
    tags: ["commercial", "retail", "gallery"],
    isFeatured: true,
    isNew: false,
  },
  {
    id: "solstice",
    name: "Solstice Smart",
    description: "Connected intelligent lighting ecosystem with full Tunable White technology and seamless smart home integration.",
    coverImage: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&q=80",
    productCount: 15,
    category: "smart",
    tags: ["smart", "tunable-white", "IoT"],
    isFeatured: false,
    isNew: true,
  },
  {
    id: "obsidian",
    name: "Obsidian Commercial",
    description: "Industrial-scale LED solutions engineered for demanding commercial environments requiring maximum efficiency.",
    coverImage: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    productCount: 56,
    category: "commercial",
    tags: ["commercial", "industrial", "high-output"],
    isFeatured: false,
    isNew: false,
  },
];

export const PROJECTS: Project[] = [
  {
    id: "four-seasons-tokyo",
    title: "Four Seasons Tokyo",
    client: "Four Seasons Hotels",
    location: "Tokyo, Japan",
    year: 2024,
    category: "hospitality",
    description: "Complete architectural lighting design for the 120,000 sq ft flagship property, featuring custom pendant installations and precision LED accent systems throughout 230 guest rooms and public spaces.",
    images: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=80",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&q=80",
    ],
    coverImage: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    products: ["aurora", "essence", "meridian"],
    tags: ["luxury", "hospitality", "custom"],
    size: "120,000 sq ft",
  },
  {
    id: "apple-store-milan",
    title: "Retail Flagship Milan",
    client: "Confidential",
    location: "Milan, Italy",
    year: 2024,
    category: "retail",
    description: "High-precision track lighting system delivering 4,000K color accuracy for product displays across 8,500 sq ft of retail space.",
    images: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=80",
      "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1200&q=80",
    ],
    coverImage: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
    products: ["meridian", "obsidian"],
    tags: ["retail", "precision", "CRI 97+"],
    size: "8,500 sq ft",
  },
  {
    id: "moma-expansion",
    title: "MoMA West Wing",
    client: "Museum of Modern Art",
    location: "New York, USA",
    year: 2023,
    category: "museum",
    description: "Tunable white gallery lighting system preserving artwork integrity while enabling dynamic temporal light environments for rotating exhibitions.",
    images: [
      "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=1200&q=80",
      "https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=1200&q=80",
    ],
    coverImage: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800&q=80",
    products: ["solstice", "essence"],
    tags: ["museum", "tunable-white", "gallery"],
    size: "45,000 sq ft",
  },
  {
    id: "equinox-hotels",
    title: "Equinox Hotel Chicago",
    client: "Equinox Hotels",
    location: "Chicago, USA",
    year: 2024,
    category: "hospitality",
    description: "Wellness-focused circadian lighting system installed across 240 rooms, optimizing human-centric light patterns for guest recovery and performance.",
    images: [
      "https://images.unsplash.com/photo-1535827841776-24afc1e255ac?w=1200&q=80",
      "https://images.unsplash.com/photo-1544458490-68767b499cda?w=1200&q=80",
    ],
    coverImage: "https://images.unsplash.com/photo-1535827841776-24afc1e255ac?w=800&q=80",
    products: ["solstice", "aurora"],
    tags: ["wellness", "circadian", "smart"],
    size: "180,000 sq ft",
  },
  {
    id: "pier-17-nyc",
    title: "Pier 17 Seaport",
    client: "Howard Hughes Corporation",
    location: "New York, USA",
    year: 2023,
    category: "commercial",
    description: "Marine-grade IP65 exterior lighting installation for the 300,000 sq ft waterfront mixed-use development.",
    images: [
      "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200&q=80",
      "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=1200&q=80",
    ],
    coverImage: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80",
    products: ["terra", "obsidian"],
    tags: ["outdoor", "waterfront", "IP65"],
    size: "300,000 sq ft",
  },
  {
    id: "stanford-med",
    title: "Stanford Medical Center",
    client: "Stanford Health Care",
    location: "Stanford, USA",
    year: 2023,
    category: "healthcare",
    description: "Human-centric healing environment with antimicrobial-rated fixtures and tunable circadian protocols proven to reduce patient recovery time.",
    images: [
      "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&q=80",
      "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=1200&q=80",
    ],
    coverImage: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
    products: ["solstice", "essence"],
    tags: ["healthcare", "circadian", "antimicrobial"],
    size: "520,000 sq ft",
  },
];

export const STATS: Stat[] = [
  {
    value: "40",
    numericValue: 40,
    suffix: "+",
    label: "Years of Innovation",
    description: "Four decades pioneering the future of architectural illumination",
  },
  {
    value: "50",
    numericValue: 50,
    suffix: "K+",
    label: "Products Engineered",
    description: "The most comprehensive luminaire portfolio in North America",
  },
  {
    value: "120",
    numericValue: 120,
    suffix: "+",
    label: "Countries Served",
    description: "Global reach with precision local expertise and support",
  },
  {
    value: "98",
    numericValue: 98,
    suffix: "%",
    label: "Client Satisfaction",
    description: "Industry-leading quality assurance and post-sale support",
  },
];

export const TECH_FEATURES: TechFeature[] = [
  {
    id: "trucolor",
    icon: "palette",
    title: "TrueColor Technology",
    description: "Proprietary phosphor engineering achieving CRI 97+ for perfect color fidelity across the full visible spectrum.",
    detail: "Our patented multi-phosphor LED arrays render colors with unprecedented accuracy, making every space come alive with the richness of natural light.",
    metric: "97+",
    metricLabel: "CRI Rating",
  },
  {
    id: "tunable",
    icon: "sun",
    title: "Tunable White Intelligence",
    description: "Dynamic 1800K-6500K color temperature control enabling human-centric lighting aligned with circadian rhythms.",
    detail: "Seamlessly transition from warm candlelight to cool daylight, synchronized with human biology for enhanced wellbeing and productivity.",
    metric: "1800K",
    metricLabel: "to 6500K",
  },
  {
    id: "smartlink",
    icon: "zap",
    title: "SmartLink Ecosystem",
    description: "Native integration with Matter, HomeKit, Alexa, and Google Home through our unified control protocol.",
    detail: "One ecosystem, infinite control. SmartLink bridges every major smart home platform with military-grade encryption and sub-50ms response latency.",
    metric: "50ms",
    metricLabel: "Response Time",
  },
  {
    id: "efficiency",
    icon: "battery",
    title: "Photon Efficiency Engine",
    description: "Advanced optical systems delivering up to 150 LPW efficacy, setting the benchmark for sustainable commercial lighting.",
    detail: "Our proprietary reflector geometry and AR-coated optics minimize photon loss while maximizing useful lumens on target.",
    metric: "150",
    metricLabel: "LPW Efficacy",
  },
  {
    id: "thermal",
    icon: "thermometer",
    title: "ThermalCore Management",
    description: "Aerospace-grade aluminum heat sinking with micro-fin geometry extending LED life beyond 100,000 hours L90.",
    detail: "Derived from thermal management research in satellite electronics, our heat sinking technology is 40% more efficient than industry standard.",
    metric: "100K",
    metricLabel: "Hour Lifespan",
  },
  {
    id: "precision",
    icon: "crosshair",
    title: "Beam Precision Optics",
    description: "PMMA micro-optic lenses engineered to ±1° angular accuracy for surgical lighting control in gallery and retail.",
    detail: "Each optical system is individually calibrated in our ISO 9001 certified facility using goniophotometric verification.",
    metric: "±1°",
    metricLabel: "Beam Accuracy",
  },
];

export const TIMELINE_EVENTS: TimelineEvent[] = [
  {
    year: "1984",
    title: "Founded in New Jersey",
    description: "WAC Lighting established with a singular focus: create the finest luminaires ever made for the American market.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",
  },
  {
    year: "1998",
    title: "LED Pioneer",
    description: "Among the first manufacturers to commercialize high-CRI LED technology, fundamentally reshaping the industry trajectory.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
  },
  {
    year: "2008",
    title: "Global Expansion",
    description: "Opened European headquarters and expanded distribution to 60 countries, establishing WAC as a truly global brand.",
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=600&q=80",
  },
  {
    year: "2015",
    title: "Smart Integration",
    description: "Launched the SmartLink platform, pioneering connected architectural lighting before IoT became mainstream.",
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80",
  },
  {
    year: "2020",
    title: "TrueColor Breakthrough",
    description: "Patented the TrueColor phosphor system achieving CRI 97+ — raising the industry standard for color fidelity.",
    image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=600&q=80",
  },
  {
    year: "2024",
    title: "The Next Chapter",
    description: "Launching Matter-native smart systems and our most energy-efficient product line in company history.",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80",
  },
];

export const NAV_ITEMS = [
  {
    label: "Products",
    href: "/products",
    megaMenu: {
      columns: [
        {
          title: "Interior",
          items: [
            { label: "Recessed Lighting", href: "/products/recessed" },
            { label: "Track Lighting", href: "/products/track" },
            { label: "Pendant Lights", href: "/products/pendant" },
            { label: "Wall Sconces", href: "/products/wall" },
            { label: "Surface Mount", href: "/products/surface" },
            { label: "Under Cabinet", href: "/products/under-cabinet" },
          ],
        },
        {
          title: "Exterior",
          items: [
            { label: "Landscape Lighting", href: "/products/landscape" },
            { label: "Outdoor Wall", href: "/products/outdoor-wall" },
            { label: "Step & Path", href: "/products/step-path" },
            { label: "Flood & Spot", href: "/products/flood-spot" },
            { label: "Post Lights", href: "/products/post" },
          ],
        },
        {
          title: "Commercial",
          items: [
            { label: "Linear Suspension", href: "/products/linear" },
            { label: "High Bay", href: "/products/high-bay" },
            { label: "Architectural Downlight", href: "/products/downlight" },
            { label: "Emergency Lighting", href: "/products/emergency" },
            { label: "Exit Signs", href: "/products/exit" },
          ],
        },
        {
          title: "Technology",
          items: [
            { label: "Smart Lighting", href: "/products/smart" },
            { label: "Tunable White", href: "/products/tunable" },
            { label: "RGBW Systems", href: "/products/rgbw" },
            { label: "Controls & Dimmers", href: "/products/controls" },
          ],
        },
      ],
    },
  },
  {
    label: "Collections",
    href: "/collections",
    megaMenu: null,
  },
  {
    label: "Projects",
    href: "/projects",
    megaMenu: null,
  },
  {
    label: "Technology",
    href: "/technology",
    megaMenu: null,
  },
  {
    label: "About",
    href: "/about",
    megaMenu: null,
  },
  {
    label: "Contact",
    href: "/contact",
    megaMenu: null,
  },
];
